part3-4team-Taskify/Taskify

- src/styles/globals.css
- 반영 브랜치
feature/GlobalStyle -> dev
---
- 변경 사항
1. 공통 color 중 text 작성에 사용되는 color들을 따로 정의했습니다.(보다 간결한 코드 작성 가능)
```
@layer utilities {
.text-black3 {
color: var(--color-black3);
}
}
```
변경 전 text에 color 적용 방법
`<button className="text-[var(--color-black3)]">로그인</button>`
변경 후 text에 color 적용 방법
`<button className="font-16r text-black3">로그인</button>`
2. font style 정의 방식을 변경하며 @apply를 삭제했습니다.(최신 버전에 맞지 않다고 판단)
변경 전/후 사용 방법은 같습니다.
---
- 테스트 결과
> [Fix] 공통 color중 text color @layer utilities로 정의

- src/components/ColumnCard/Card.tsx
- src/components/ColumnCard/Column.tsx
- src/pages/dashboard.tsx
- src/types/task.ts
- 공통적으로 사용하는 타입을 한 파일에서 관리하도록 리팩토링했습니다.
- 중복된 타입을 제거하고, 타입 관련 에러를 수정했습니다.
- 공통 타입을 types.ts에 통합 관리하도록 수정
- 기존 컴포넌트 내 개별 선언된 타입 제거 및 통합된 타입으로 교체
- 변경으로 인한 타입 에러 수정 완료
> [Refector, Fix] Page: 대시보드 페이지 타입 정의 및 통합

- .github/workflows/deploy.yml
이미지와 같이 개인 레포지토리에 push되지 않는 error 발생
해당 문서의 아래 부분
```
source-directory: 'output'
destination-github-username: MINJI121
destination-repository-name: Taskify
user-email: ${{ secrets.EMAIL }}
commit-message: ${{ github.event.commits[0].message }}
target-branch: main
```
최신 문법인 카멜 케이스로 변경
ex) destinationGithubUsername: 'my-username'
> [Fix] vercel, git actions 배포: Update deploy.yml

- build.sh
배포 과정에서 개인 레포지토리로 push되지 않는 에러 해결을 위해
build 파일 내 레포지토리 명의 대괄호 삭제
> [Fix] vercel, git actions 배포: Update build.sh

- src/components/landing/Section1.tsx
- src/pages/mydashboard.tsx
landing 페이지의 Section.tsx 파일에 로그인 상태 추가
로그인 상태에서 '로그인하기' 버튼 -> '대시보드 이동하기' 버튼으로 전환
테스트 완료
클릭 시 페이지 이동 정상 동작
> [Feat] landing: 로그인 상태일 때 '대시보드 이동하기' 버튼으로 전환

- src/components/card/ChangePassword.tsx
- src/components/card/Profile.tsx
- src/components/common/CustomToastContainer.tsx
- src/components/gnb/HeaderDashboard.tsx
- src/components/gnb/MemberListMenu.tsx
- src/components/gnb/MembersProfileIconList.tsx
- src/components/gnb/ProfileIcon.tsx
- src/components/input/Input.tsx
- src/components/table/member/MemberList.tsx
- src/pages/mypage.tsx
- src/styles/globals.css
1. mypage: 전반적인 css & 반응형 디자인 수정
2. mypage: 돌아가기 버튼 추가
3. mypage_Profile, ChangePassword: 폰트, 컬러, 여백 등 규격에 맞게 수정
4. mypage_Profile, ChangePassword: 변경 성공 시 토스트 발생, 토스트 사라지면 자동 새로고침
5. ChangePassword_새 비밀번호 input: Input 컴포넌트를 커스텀해 사용하는 것으로 리팩토링(규격이 달라서 통일함)
6. Gnb_MembersProfileIconList: 모바일 이하에서는 최대 3개 출력으로 반응형 변경
테스트 완료
닉네임 변경, 비밀번호 변경 등 기능 정상 동작
> [Feat, Style] mypage: css & 반응형 수정, 정보 변경 시 toast 발생, toast 사라지면 새로고침 / Gnb: 멤버 목록 반응형 적용

- src/components/card/ChangePassword.tsx
- src/components/card/Profile.tsx
- src/components/common/CustomToastContainer.tsx
- src/components/input/Input.tsx
- src/pages/login.tsx
1. 프로필 컴포넌트에서 제한 용량 초과 이미지 업로드 시 에러 발생,
3.5MB의 제한 용량 초과 시 에러 토스트 메시지 발생하도록 처리.
업로드 실패 시 미리보기 이미지 변경되지 않도록 수정.
2. Input 컴포넌트에서 forceInvarid(유효성 검사) props 전달되지 않고 있어 콘솔 에러 발생, props에 추가해 처리.
3. ChangePassword 새 비밀번호 확인 연산자 코드 단축 리팩토링
4. 토스트 표시 시간 3000밀리초로 변경
테스트 완료
> [Fix, Refactor] Profile: 이미지 업로드 제한 용량 초과 시 에러 처리 / Input: Props 미전달 콘솔 에러 처리

- src/components/table/InviteRecords.tsx
- src/components/table/TablePagination.tsx
- src/components/table/member/MemberList.tsx
- src/pages/dashboard/[dashboardId]/edit.tsx
1. edit_InviteRecords, MemberList: min-h 설정으로 리스트 증가 시 컨테이너 높이 유동 조절되도록 변경
2. edit_Pagination: 버튼 비활성화 시 토글 효과 제거되도록 변경
수정 전/후 테스트 완료
> [Style] edit: 태블릿, 모바일에서 구성원, 초대 내역 텍스트 이탈 문제 수정

- src/components/button/CardButton.tsx
- src/components/button/DashboardAddButton.tsx
- src/components/columnCard/Column.tsx
- src/components/gnb/HeaderDashboard.tsx
- src/components/sideMenu/SideMenu.tsx
- src/components/table/invited/InvitedDashBoard.tsx
- src/pages/dashboard/[dashboardId]/edit.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
- src/pages/mydashboard.tsx
- src/pages/mypage.tsx
- src/styles/globals.css
1. mydashboard_CardButton: 카드 버튼 상하 여백 조정
2. SideMenu: 상하 스크롤 제거, 긴 대시보드 제목 말줄임표 적용, 페이지 이동 시 페이지네이션 버튼 밀림 현상 수정
3. HeaderDashboard: 긴 대시보드 제목 말줄임표 적용
4. 전체 페이지: 배경색 --color-violet5: #f5f2fc 로 변경
수정 전
수정 후
> [Refactor, Style] mydashboard: 카드 간 여백 조정 / SideMenu: 상하 스크롤 제거, 제목 말줄임표 적용, 페이지 버튼 밀림 현상 수정 / 전체: 배경색 변경

- src/components/button/CardButton.tsx
- src/components/button/ColumnsButton.tsx
- src/components/button/TodoButton.tsx
- src/components/columnCard/Card.tsx
- src/components/columnCard/CardList.tsx
- src/components/columnCard/Column.tsx
- src/components/gnb/HeaderDashboard.tsx
- src/components/gnb/MemberListMenu.tsx
- src/components/input/Input.tsx
- src/components/sideMenu/SideMenu.tsx
- src/pages/dashboard/[dashboardId]/edit.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
- src/pages/login.tsx
- src/pages/signup.tsx
1. Column: 가로 스크롤 제거 / 디자인 변경_여백 & 반응형 조정
2. dashboardindex_ColumnsButton: 하단 고정 버튼이 사이드메뉴 위로 오는 문제 수정 / 중앙 정렬 설정
3. SideMenu: 맨 위로 오게 하기 위해 z-20 추가
4. signup_Input: 회원가입 페이지 스크롤 제거 목적, 인풋 라벨 gap 1로 조정
5. Card: 제목 생략 모바일에 적용 안 됨, max-w 추가해 적용 / text 색상 & 사이즈 수정
6. HeaderDashboard_UserMenu, MemberListMenu: 메뉴 열린 상태에서 onClick 재실행 시 닫히도록 변경
> [Refactor, Style] DropdownMenu: 재 클릭 시 닫힘 / Column: 여백, 반응형 조정 / Card: 긴 제목 생략 모바일에도 적용

- src/components/card/ChangePassword.tsx
- src/pages/mypage.tsx
useEffect(() => {
if (isInitialized && user) {
fetchDashboards();
fetchUserData();
}
}, [isInitialized, user]);
user 상태 변경 연쇄 현상으로 useEffect가 무한 실행되는 에러 발견
의존성 배열에서 user 제거해서 fix,
Profile 컴포넌트에서 이미 실행하는 fetchUserData();도 불필요해 제거함.
> [Fix] mypage: api 요청 무한 루프 에러 수정

- package-lock.json
- package.json
- src/components/button/CardButton.tsx
- src/components/button/SortableCardButton.tsx
- src/pages/mydashboard.tsx
- 나의 대쉬보드 페이지에 D&D 를 적용하였습니다. 
- 대시보드 이동 클릭과 드래그 충돌 방지를 위해  distance: 5 5px 이상 이동시 드래그 되도록 하였습니다.
- SortableCardButton.tsx 를 새로 작성하여 dragHandleProps → attributes, listeners props 전달 방식을 변경하였습니다.
- 아직 D&D로 변경된 순서를 api에 저장하지는 못합니다. 추후 수정예정
- npm install @dnd-kit/core @dnd-kit/sortable @dnd-kit/modifiers 부탁드리겟습니다.
> [Feat, Refector] D&D 적용 및 파일수정

- src/components/modal/ChangeBebridge.tsx
- src/components/modal/DeleteDashboardModal.tsx
- src/components/modal/DeleteMemberModal.tsx
- src/components/table/InviteRecords.tsx
- src/components/table/invited/InvitedDashBoard.tsx
- src/components/table/member/MemberList.tsx
- src/pages/dashboard/[dashboardId]/edit.tsx
- src/pages/mydashboard.tsx
- src/pages/mypage.tsx
1. edit, mydashboard: 대시보드 수정, 초대 취소, 수락, 거절, 멤버 삭제 시 새로고침으로 반영 -> 새로고침 없이 즉시 반영되게 변경
2. edit_MemberList: 멤버 삭제 시 종종 삭제한 멤버 위나 아래의 멤버가 삭제되는 버그 발견. 삭제 확인 모달 오픈 시 모달 내부에서 id값이 잘못 고정되는 현상이 원인으로 추정. `id={selectedMemberId}` 선택한 id를 삭제하도록 fix
> [Fix, Refactor] edit, mydashboard: 페이지 변경사항 즉시 반영 / edit_MemberList: 멤버 삭제 시 다른 멤버가 삭제되는 버그 fix

- src/components/button/TodoButton.tsx
- src/components/columnCard/Card.tsx
- src/components/columnCard/CardList.tsx
- src/components/columnCard/Column.tsx
- src/components/modalDashboard/CardDetailModal.tsx
- src/components/modalInput/AssigneeSelect.tsx
- src/components/modalInput/ModalInput.tsx
- src/components/modalInput/StatusSelect.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
- src/pages/login.tsx
- src/pages/signup.tsx
- src/styles/globals.css
1. Column, CardList: 카드리스트 내부 스크롤을 칼럼에 적용(스크롤에 카드 오른쪽이 잘려 보이는 현상 해결 목적)
2. Card: 미리보기 이미지 크기, 내부 아이템 여백 등 반응형 디자인 수정
3. ModalInput: 필수 입력값 표시 '*' 색상 통일(기존 바이올렛, 프라이머리 혼용됨)
4. toast: text 두께 r -> m 변경
5. login, signup: 배경색 gray -> white 변경
> [Style, Refactor] Column: 카드리스트 스크롤 칼럼으로 이동 / Card: 반응형 디자인 수정

- src/components/landing/LandingMain.tsx
- src/components/landing/Section2.tsx
- src/components/landing/Section3.tsx
- 랜딩페이지 하단부 그리드와 중간의 section2의 박스 정렬을 수정하였습니다.
- ![image](https://github.com/user-attachments/assets/81b65b80-9201-40ec-b9df-3e953d1ea5cf)
- ![image](https://github.com/user-attachments/assets/6a5ee86a-9cce-4d55-8521-aec6e0b6b912)
- ![image](https://github.com/user-attachments/assets/e065cbf6-3bb9-4e6d-8a59-67963985f295)
> [Fix] 랜딩페이지 정렬 수정

- src/components/modal/ChangeBebridge.tsx
- src/components/modal/InviteDashboard.tsx
- src/components/modal/NewDashboard.tsx
- src/components/modalInput/ModalInput.tsx
- src/components/table/InviteRecords.tsx
- src/components/table/TablePagination.tsx
- src/components/table/member/MemberList.tsx
- src/components/table/member/RandomProfile.tsx
- src/pages/login.tsx
- src/pages/signup.tsx
1. signup, login: 로고 이미지 크기 반응형 조정(모바일 사용성 향상)
2. edit_ChangeBebridge, MemberList, InviteRecords: 내부 컨테이너 생성해 아이템 정렬 통일
3. ChangeBebridge, NewDashboard: 대시보드 이름 30자 제한 적용
4. InviteRecords: 초대 내역 즉시 반영
5. edit_Pagination: 버튼 비활성화 시 cursor-defalt 변경, toggle 효과 삭제
> [Style, Refactor] edit: 내부 컴포넌트 정렬 통일 / NewDashboard: 대시보드 이름 30자 제한 / InviteRecords: 초대 내역 즉시 반영

- src/components/columnCard/CardList.tsx
- src/components/sideMenu/SideMenu.tsx
- 칼럼 상세 페이지에 D&D기능을 삭제하였습니다.
- 사이드 메뉴의 접기 상태일 때 대시보드 목록의 정렬이 틀어짐을 수정햇습니다.
- 사이드 메뉴 접기 상태일때 모바일 로고로 변경하였습니다.
- ![image](https://github.com/user-attachments/assets/e52b9ed2-7681-48b7-a4c2-982f53102cd6)
- ![image](https://github.com/user-attachments/assets/3ecbcc12-9f23-4779-a57a-f5e40415e813)
> [fix, Refector] 사이드 메뉴 정렬 및 로고 변경, 칼럼상세 D&D삭제

- src/components/card/Profile.tsx
- src/components/modal/ChangeBebridge.tsx
- src/components/modalDashboard/CardDetail.tsx
- src/components/modalDashboard/CardDetailModal.tsx
- src/components/modalDashboard/CommentList.tsx
- src/components/modalDashboard/ProfileIcon.tsx
- src/components/modalDashboard/Representative.tsx
- src/components/modalDashboard/UpdateComment.tsx
- src/components/modalInput/CardInput.tsx
- src/components/modalInput/ModalInput.tsx
- src/components/modalInput/StatusSelect.tsx
- src/components/modalInput/chips/ColorTagChip.tsx
- src/components/modalInput/chips/ColumnNameTag.tsx
- src/types/users.ts
1. edit_Profile: 기존 프로필 이미지가 없을 때는 닉네임 변경이 되지 않아, 가능하도록 수정.
2. CardDetailModal: 전체적인 CSS 수정과 반응형 디자인 / 수정 과정에서 컴포넌트 분리.
카드 info 컴포넌트(Representative.tsx), 칼럼명 태그 컴포넌트(ColumnNameTag.tsx)
ColumnNameTag.tsx - 카드 편집 모달 내부 div 분리해서 재사용
3. CardDetailModal_CommentList: 작성된 댓글 없을 시 안내 메시지 표시
/ 스크롤-히든 제거 & 스크롤 표시되게 변경(추가 댓글이 있을 경우 사용자에게 알려주기 위함)
수정 전
수정 후
> [Style, Refactor] CardDetailModal: 전체적인 CSS 수정과 반응형 작업 / edit: 프로필 이미지 없이도 닉네임 변경

- src/components/columnCard/Card.tsx
- src/components/columnCard/Column.tsx
- src/components/modal/DeleteMemberModal.tsx
- src/components/modalDashboard/CardDetail.tsx
- src/components/modalDashboard/CardDetailModal.tsx
- src/components/modalDashboard/PopupImageModal.tsx
- src/components/modalDashboard/ProfileIcon.tsx
- src/components/modalDashboard/Representative.tsx
- src/components/modalInput/ModalInput.tsx
- src/components/modalInput/chips/ColorTagChip.tsx
- src/components/modalInput/chips/ColumnNameTag.tsx
- src/components/table/member/RandomProfile.tsx
- src/hooks/useClosePopup.tsx
1. CardDetailModal: 이미지 클릭 시 전체 이미지 확인되는 모달 오픈
(이미지 비율에 따라 이미지의 일부만 확인 가능한 불편 해소 목적)
3. ModalInput: 태그 개수 4개 제한 & 백스페이스로 삭제 기능 추가 & 글자수 10자 제한 추가
4. Card: 태그 bg, text 정보 하드코딩 제거, getTagColor 받도록 수정
-> 모든 색상 순서대로 출력(기존 태그 색상이 순서대로 출력되지 않는 문제 해결)
& 모바일에서 태그 영역이 길면 잘리는 현상 fix(whitespace + max-w)
- 태그 수정 전
- 태그 수정 후
- 이미지 팝업 추가
바깥 클릭 또는 esc 키다운 시 닫힘
> [Feat, Rafactor] CardDetailModal: 이미지 클릭 시 팝업 오픈 / ModalInput: tag 개수 4개 제한 & 백스페이스 삭제 기능 추가

- src/components/modalDashboard/CardDetail.tsx
- src/components/modalDashboard/CardDetailModal.tsx
- src/components/modalDashboard/CommentList.tsx
- src/components/modalDashboard/Representative.tsx
- src/components/modalInput/CardInput.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
1. CardDetail: 기존 제목 - 태그 - 내용 - 이미지 순 출력에서, 이미지 하단에 태그 출력되게 디자인 변경
2. dashboardindex: 칼럼 추가 버튼 태블릿 이하 하단 고정 출력 -> 일반 출력 변경(칼럼은 카드와 달리 생성할 일이 적기 때문에, 고정 출력이 오히려 불편을 야기하는 것 같아 수정)
& 헤더, 사이드메뉴 고정(h-screen 추가)
> [Style, Refactor] CardDetail: 태그 영역 하단 이동 / dashboardindex: 칼럼 추가 버튼 반응형 출력 변경, 헤더&사이드메뉴 고정

- src/components/Layouts/DashboardLayout.tsx
- src/components/button/GuestModeButton.tsx
- src/components/sideMenu/SideMenu.tsx
- src/pages/404.tsx
- src/pages/_app.tsx
- src/pages/dashboard/[dashboardId]/edit.tsx
- src/pages/dashboard/[dashboardId]/index.tsx
- src/pages/login.tsx
- src/pages/mydashboard.tsx
- src/pages/mypage.tsx
- src/pages/signup.tsx
1. _app.tsx에 높이 계산식 추가
`window.innerHeight * 0.01`을 vh 변수에 저장하는 계산식을 추가했습니다.
resize(주소창 표시, 숨김 등 윈도우 내부 높이 변경) 발생 시 setVH를 재실행합니다.
3. 모든 컴포넌트 `h-screen` -> `h-[calc(var(--vh)_*_100)]` 교체
(사파리에서 주소창 영역만큼의 스크롤이 발생하던 문제 해결)
- 수정 전
- 수정 후
> [Refactor] 사파리 대응 세로스크롤 방지 목적 window innerHeight 기준 높이 계산식 추가

- src/components/modalDashboard/CardDetailModal.tsx
- src/components/modalInput/TaskModal.tsx
- src/components/sideMenu/DashboardItem.tsx
- src/components/sideMenu/SideMenu.tsx
- src/hooks/useCardDetail.ts
- src/hooks/useCardDetailState.ts
- src/hooks/useColumnStatus.ts
- src/hooks/usePagination.ts
- src/hooks/useTaskForm.ts
- src/lib/dashboardUtils.ts
- src/lib/useDashboardDragHandler.ts
- src/pages/mydashboard.tsx
- MyDashboardPage.tsx (나의 대시보드 페이지)
D&D 핸들러 분리
useDashboardDragHandler 커스텀 훅으로 handleDragEnd 로직 분리
검색 필터링 useMemo 최적화, 대시보드 리스트 필터링 useMemo 적용
선택된 대시보드 정보 selectedDashboard 객체로 통합 관리
- SideMenu.tsx (사이드 메뉴)
로고 렌더링 함수 분리 → renderLogo()
접기/펼치기 버튼 분리 → renderCollapseButton()
추가 버튼 함수 분리 → renderAddButton()
대시보드 아이템 분리 → renderDashboardItem()
페이지네이션 로직 분리 → usePagination 커스텀 훅으로 리팩토링
- TaskModal.tsx (할 일 생성/수정 모달)
useTaskForm 커스텀 훅으로 내부 상태 및 핸들러 분리
Column 매칭 로직 분리 - useColumnStatus 훅으로 matchedColumn, updatedColumnId 관리
- CardDetailModal.tsx (카드 상세 모달)
useCardDetailState로 cardData, columns, members 상태 분리
댓글 및 모달 상태/로직 분리
useCardDetail 훅으로 아래 상태 및 기능 분리: 댓글 작성, 수정 모달, 삭제 모달, 메뉴 팝업 열기, 삭제 처리
> [Refector] 컴포넌트 로직분리 

- src/api/members.ts
- src/components/modal/DeleteDashboardModal.tsx
- src/components/modal/DeleteModal.tsx
- src/components/modal/NewDashboard.tsx
- src/components/modalDashboard/CardDetailModal.tsx
- src/components/modalDashboard/CommentList.tsx
- src/components/modalDashboard/Representative.tsx
- src/components/modalDashboard/UpdateComment.tsx
- src/components/modalInput/ModalInput.tsx
- src/components/modalInput/TaskModal.tsx
- src/hooks/usePostGuard.ts
- src/hooks/useTaskForm.ts
- src/pages/dashboard/[dashboardId]/index.tsx
- src/pages/login.tsx
- src/pages/signup.tsx
1. ModalInput: 카드 수정 시 제목 인풋창 변화 발생 전까지 현재 글자수 0으로 표시되던 문제 fix
2. usePostGuard 공통 훅 생성: 회원가입, 로그인, 대시보드 생성, 칼럼 생성, 카드 생성에 post 요청 중복 방지 적용
3. CommentList: 댓글 수정 권한 버그 fix
(전달받는 id 올바르게 수정)
4. CardDetailModal_Representative: 모바일에서 담당자 필드와 마감일 필드 수평 정렬 조정
(담당자 필드의 프로필아이콘 h-6에 맞춰 h-6 래퍼로 date 감쌈)
- postGuard 적용 전
- postGuard 적용 후
- 댓글 작성 권한 fix 전
- 댓글 작성 권한 fix 후
> [Fix, Refactor, Style] 전체: post 요청 중복 방지 / CommentList: 카드 담당자=댓글 작성자일 때만 수정/삭제되던 버그 fix
