part3-4team-Taskify/Taskify

src/pages/404.tsx

NotFound -> dev
pages 폴더에 404.tsx 파일 추가
테스트 완료

[Feat] 404 Not Found 에러 페이지 제작

---

src/pages/signup.tsx

SignUp -> dev
디자인 완료, 기능 X
1. Input 컴포넌트 연동
2. 비밀번호 확인 Input과 불일치 시 경고 메시지 추가
3. 체크박스 디자인 추가
테스트 완료

[Feat] signup 페이지 디자인

---

src/components/landing/Footer.tsx
src/components/landing/LandingMain.tsx
src/components/landing/Section1.tsx
src/components/landing/Section2.tsx
src/components/landing/Section3.tsx
src/pages/index.tsx

랜딩 페이지 작성 완료 했습니다 컴포넌트 파일에 footer 작성 하였으니 필요하시면 가져다 쓰시면 될거 같습니다. 
반응형 작업까지 완료 한 상태입니다.

[Feat] 랜딩 페이지 추가

---

src/components/Gnb/HeaderBebridge.tsx
src/components/Gnb/HeaderDashboard.tsx
src/components/Gnb/HeaderDefault.tsx
src/components/Gnb/HeaderDefaultBk.tsx
src/components/Gnb/HeaderMypage.tsx

Header: 랜덤프로필 컴포넌트 더미 데이터 연결 & 이미지 절대경로로 수정

[Fix] Header: 랜덤프로필 컴포넌트 더미 데이터 연결 & 이미지 절대경로로 수정

---

src/components/ModalInput/AssigneeSelect.tsx
src/components/ModalInput/ModalInput.tsx
src/components/ModalInput/ModalTextarea.tsx
src/components/SideMenu/ComminLayout.tsx
src/components/SideMenu/SideMenu.tsx

AssigneeSelect.tsx  unused useEffect
ModalInput.tsx 조건문 내 useState
ModalTextarea.tsx unused inputClassNames
버셀 배포 오류 내역 확인후 수정햇습니다.

[Fix] Vercel 오류 해결 

---

src/pages/login.tsx

1. 아직 사용하지 않는 훅 제거
2. 링크 태그 `<a>`에서 `<Link>`로 교체

[Fix] login: 배포 에러 해결 목적의 파일 수정

---

build.sh

vercel과 git actions로 organization 레포지토리 무료 배포하기

[Feat] Create build.sh

---

.github/workflows/deploy.yml

vercel과 git actions로 organization 레포지토리 무료 배포하기

[Feat] Create deploy.yml

---

.github/workflows/deploy.yml

[Fix] vercel, git actions 배포: Update deploy.yml

---

src/components/button/CardButton.tsx
src/components/button/ColumnsButton.tsx
src/components/button/DashboardAddButton.tsx

CardButton=비브리지 버튼
ColumnsButton=새로운 칼럼 추가
DashboardAddButton=새로운 대시보드 추가
DashboardDeleteButton=대시보드 삭제
TodoButton=플러스 버튼

[Style] 버튼 플러스이미지 백그라운드설정

---

.github/workflows/deploy.yml

Organization 레포의 dev 브랜치 ->개인 레포의 main 브랜치에 push해 build하는 파일 재생성함

[Fix] vercel, git actions 배포: Create deploy.yml

---

src/components/common/Modal/Modal.tsx

[Style] Modal: 스타일 변경

---

src/api/members.ts
src/components/Gnb/HeaderBebridge.tsx
src/components/card/Profile.tsx
src/components/common/Modal/Modal.tsx
src/components/modal/NewDashboard.tsx
src/components/table/invited/InvitedDashBoard.tsx
src/components/table/invited/NoResultDashBoard.tsx
src/components/table/member/MemberList.tsx
src/components/table/member/RandomProfile.tsx
src/pages/dashboard/[dashboardId]/edit.tsx
src/pages/dashboard/[dashboardId]/index.tsx
src/pages/mypage.tsx
src/pages/test.tsx

- Modal : 새로운 대시보드
- Header : HeaderBebrige.api

Moal : 새로운 대시보드(위치, 뒷배경 수정) + Header : HeaderBebridge api 데이터 저장

---

src/components/input/Input.tsx
src/pages/mydashboard.tsx

인풋 컴포넌트 오류 메세지 간격 수정
나의 대시보드 페이지 작성완료 
api 연동 추가를 해야함 추후 연동 예정

[Feat] 나의 대쉬보드 페이지 작성

---

src/api/axiosInstance.ts
src/api/sidemenu.ts
src/components/SideMenu/SideMenu.tsx
src/pages/mydashboard.tsx

- 사이드 메뉴 API연결
- axiosistance에서 디버깅용 로그 출력부분 추가

[Feat] 사이드 메뉴 Api연결

---

src/components/button/CardButton.tsx
src/components/sideMenu/SideMenu.tsx
src/pages/mydashboard.tsx

- 나의 대쉬보드 페이지 완성 했습니다.
- cardButton.tsx 파일의 API연동을 하였습니다. 
- cardButton.tsx 의 디자인이 시안과 맞지 않아 조금 수정하였습니다. 
- 이전 사이드 메뉴에 연결되었던 API연동을 페이지에서 연동이 가능하게 하여 실시간으로 반영되게 했습니다.
https://github.com/user-attachments/assets/298e9bd6-abb7-45a5-8003-70fbdc2fc865

[Feat] 나의 대쉬보드 페이지

---

src/components/gnb/HeaderDashboard.tsx
src/components/modal/MypageModal.tsx

헤더 내부 유저 info 클릭 시 /mypage 이동 기능 추가
cursor-default 지정(cursor-text 방지)
테스트 완료

[Feat] Gnb: 유저 정보 섹션 클릭 시 mypage 이동 기능 추가

---

src/api/card.ts
src/components/modalInput/ModalImage.tsx
src/components/modalInput/TaskModal.tsx

- TaskModal.tsx 할일 수정 모달에 api를 연결 하였습니다.
- 모달을 띄우는 컴포넌트 에서 updateCard를 api 로 호출하고 사용하시면 됩니다.

[feat] 할일 수정모달 api연결

---

src/components/gnb/Avatars.tsx
src/components/table/member/RandomProfile.tsx

멤버 목록 아이콘에서 image가 화면 전체에 출력되던 오류 디버깅
디버깅 과정에서 아이콘 찌그러짐 오류 디버깅
##테스트 유무
테스트 완료

[Fix] Gnb: 멤버 목록 프로필 이미지 출력 오류 디버깅, 정원형 출력을 위한 리팩토링

---

src/components/common/LoadingSpinner.tsx
src/components/gnb/HeaderDashboard.tsx
src/components/gnb/MemberListMenu.tsx
src/components/gnb/UserMenu.tsx
src/hooks/useAuthGuard.ts
src/pages/_app.tsx
src/pages/mydashboard.tsx

[Feat, Style, Refactor] 비로그인 상태에서 페이지 접근 시 화면 깜빡임 현상 수정, 로딩 스피너 추가

---

src/components/sideMenu/SideMenu.tsx

[Feat] 사이드메뉴 접기/펴기

---

src/components/columnCard/AddColumnModal.tsx
src/components/columnCard/ColumnDeleteModal.tsx
src/components/columnCard/ColumnManageModal.tsx
src/components/modal/ChangeBebridge.tsx
src/components/modal/Modal.tsx
src/components/modal/NewDashboard.tsx
src/pages/dashboard/[dashboardId]/index.tsx

- 새 컬럼 생성, 컬럼 관리, 컬럼 삭제 확인 모달 반응형
- 새 대시보드 생성 modal 색상 hover 효과 추가

[Refector] Modal: hover 효과 / Colum : 반응형

---

src/components/button/PaginationButton.tsx
src/components/gnb/Avatars.tsx
src/components/gnb/HeaderDashboard.tsx
src/pages/dashboard/[dashboardId]/edit.tsx

1. HeaderDashboard에 variant="edit" 종류 추가, edit 페이지에서 헤더 종류 변경
2. 관리 모드 버튼 스타일 수정
3. MemberAvatars -> MemberList 컴포넌트 이름 변경

[Refactor, Style] Gnb: 헤더 종류 추가, 관리 모드 버튼 스타일 수정

---

src/components/modalInput/ToDoModal.tsx
src/components/sideMenu/SideMenu.tsx
src/components/table/invited/InvitedDashBoard.tsx
src/pages/mydashboard.tsx

- 사이드 메뉴 접기버튼의 배치를 바꿧습니다.
- 대시보드 페이지 네이션 버튼을 center 로 위치를 변경하였습니다.
- 배포에러를 수정하였습니다.

[Style Fix] 사이드 메뉴, 마이대시보드 디자인 수정

---

src/components/button/CardButton.tsx
src/components/common/CustomToastContainer.tsx
src/components/gnb/HeaderDashboard.tsx
src/components/gnb/MemberListMenu.tsx
src/components/gnb/UserMenu.tsx
src/components/input/Input.tsx
src/components/modal/DeleteModal.tsx
src/pages/_app.tsx
src/pages/mydashboard.tsx
src/styles/globals.css

1. mydashboard 페이지에서 사용할 삭제 모달 컴포넌트 분리
2. _app.tsx에 기본 출력 토스트 설정 추가
3. globals.css에 토스트 디자인 추가
테스트 완료

[Feat] Modal: DeleteModal 컴포넌트 추가 / toast: 커스텀 토스트 추가 / 배포 에러 fix

---

src/components/columnCard/Column.tsx

[Refactor] teamId 인자 제거

---

src/components/modal/DeleteDashboardModal.tsx
src/components/modalDashboard/CardDetailModal.tsx

[Fix] 배포 에러 fix

---

src/components/modalInput/ModalImage.tsx
src/components/modalInput/TaskModal.tsx
src/components/modalInput/ToDoModal.tsx
src/pages/signup.tsx

[Fix] 배포 에러 fix 목적 불필요한 코드 제거

---

src/components/modalInput/ToDoModal.tsx

[Fix] 배포 에러 fix 목적, 불필요한 코드 제거

---

src/api/auth.ts
src/pages/login.tsx

[Test] 배포 환경에서 로그인 실패 에러 발생, 테스트용 코드 추가

---

src/api/card.ts

[Fix] Update card.ts

---

src/api/card.ts

[Fix] CardType 이름 변경이 api 파일에 반영되지 않은 점 수정

---

src/api/auth.ts
src/api/axiosInstance.ts

[Fix] base URL 수정

---

src/components/button/ColumnsButton.tsx
src/components/button/TodoButton.tsx
src/components/columnCard/Column.tsx
src/components/common/CustomToastContainer.tsx
src/pages/dashboard/[dashboardId]/index.tsx

[Style] Card: alert를 toast로 변경  Button: 커서 변경

---

src/api/statusOptions.ts
src/components/modalInput/StatusSelect.tsx
src/components/sideMenu/SideMenu.tsx
src/pages/mydashboard.tsx

- 나의 대쉬보드 페이지 css 수정하였습니다.
- 사이드 메뉴 접기 펴기 버튼을 모바일 버전에서는 안보이도록 수정하였습니다.
- vercel 오류를 수정하였습니다.

[Fix] vercel 오류 수정및 사이드메뉴, 나의 대쉬보드 수정

---

src/components/modalDashboard/CardDetail.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/modalInput/CardInput.tsx
src/pages/dashboard/[dashboardId]/index.tsx

- title과 버튼 정렬 맞추기
- 수정 삭제하기 버튼 커서 변경
- 이미지 크기 조정 등..
- 전체적인 정렬 맞추기
- 모바일 반응형
- status, tag 불러오기

[Style] 카드 상세모달 스타일 수정

---

src/components/modal/NewDashboard.tsx
src/components/sideMenu/SideMenu.tsx
src/pages/mydashboard.tsx

[Fix] 버셀 오류 수정

---

src/components/gnb/MembersProfileIconList.tsx
src/components/gnb/ProfileIcon.tsx
src/components/modal/DeleteModal.tsx
src/components/modal/NewDashboard.tsx
src/components/table/member/RandomProfile.tsx
src/pages/mydashboard.tsx

뉴대시보드 컴포넌트의 대시보드 생성하기 api를 dashboards.ts와 연동, 불필요한 코드 삭제

[Fix] 대시보드 api 호출 에러 fix

---

src/components/modal/NewDashboard.tsx

api 파일 연동하며 teamId 인자가 불필요해져 제거했습니다.

[Fix] NewDashboard: 불필요한 코드 제거

---

src/components/button/CardButton.tsx
src/components/button/DashboardAddButton.tsx
src/components/columnCard/Column.tsx
src/components/modal/ChangeBebridge.tsx
src/components/modal/DeleteDashboardModal.tsx
src/components/modal/DeleteMemberModal.tsx
src/components/modal/NewDashboard.tsx
src/components/modalInput/ModalImage.tsx
src/components/table/InviteRecords.tsx
src/components/table/invited/InvitedDashBoard.tsx
src/pages/dashboard/[dashboardId]/index.tsx

1. 배포 에러 fix
2. InvitedDashboard, ChangeBebridge: setTimeout 시간 수정
테스트 완료

[Fix, Refactor] 배포 에러 fix: 불필요한 코드 제거 / InvitedDashboard, ChangeBebridge: toast 소멸 후 새로고침 되도록 수정

---

src/components/button/DashboardAddButton.tsx

1. DashboardAddButton.tsx의 아무것도 정의되지 않은 타입 선언 제거

[Fix] 불필요한 타입 선언 제거

---

src/api/columns.ts
src/pages/dashboard/[dashboardId]/index.tsx

[Refector]할 일 생성모달 z-index수정

---

src/api/columns.ts
src/components/modalDashboard/CardDetailModal.tsx

[Fix] CardDetailModal: 카드 수정 시 이미지 없으면 에러 발생 fix, 변경사항 있을 때만 새로고침되도록 변경

---

src/components/modalDashboard/CardDetailModal.tsx

[Fix] CardDetailModal: 불필요한 코드 제거

---

src/pages/index.tsx

[Fix] 랜딩 시간 단축

---

src/components/card/ChangePassword.tsx
src/components/card/Profile.tsx
src/components/common/CustomToastContainer.tsx
src/components/modal/ChangeBebridge.tsx
src/components/modal/InviteDashboard.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/table/invited/InvitedDashBoard.tsx

초대 성공 후 모달 즉시 닫힘
(초대 성공 후 새로고침까지 모달이 닫히지 않아 이동할 수 없는 불편 개선)

[Refactor] InviteDashboard: 초대 성공 시 모달 바로 닫히게 변경

---

README.md

[Fix] readme 수정

---

src/pages/dashboard/[dashboardId]/edit.tsx
src/pages/dashboard/[dashboardId]/index.tsx
src/pages/mypage.tsx

- 각 페이지별 사이드 메뉴 갱신 안돼는 문제를 해결하였습니다.

[Fix] 페이지별 사이드메뉴 갱신 추가

---

src/pages/mypage.tsx

[Fix] mypage: 모바일 환경에서 사이드메뉴 가로스크롤 현상 수정

---

src/pages/mypage.tsx

[Fix] mypage: 세로 스크롤 추가

---

src/pages/dashboard/[dashboardId]/edit.tsx

px-[50px] -> px-[20px]
before
after
테스트 완료

[Style] edit: 모바일 레이아웃 깨짐, 패딩 값 조절

---

src/components/modal/InviteDashboard.tsx

새로고침하지 않아도 초대 반영됨, 불필요한 리로드 제거, 사용성 개선

[Refactor] 초대 성공 시 새로고침 기능 제거

---

src/pages/signup.tsx

[Fix] 비밀번호 불일치 시에도 회원가입 성공 에러 수정

---

src/components/card/ChangePassword.tsx
src/components/input/Input.tsx

[Fix, Refactor] 조건문 단축, 배포 에러 fix

---

src/components/card/Profile.tsx
src/styles/globals.css

[Style] 토스트 길이에 따라 width 늘어나도록 수정, 줄바꿈 허용 변경, 최대 너비 설정

---

src/components/button/BackButton.tsx
src/components/card/ChangePassword.tsx
src/components/card/Profile.tsx
src/components/landing/LandingMain.tsx
src/components/landing/Section1.tsx
src/components/landing/Section2.tsx
src/components/landing/Section3.tsx
src/components/modal/ChangeBebridge.tsx
src/components/table/InviteRecords.tsx
src/components/table/invited/InvitedDashBoard.tsx
src/components/table/member/MemberList.tsx
src/pages/dashboard/[dashboardId]/edit.tsx
src/pages/dashboard/[dashboardId]/index.tsx
src/pages/mydashboard.tsx
src/pages/mypage.tsx

1. mypage, edit: 돌아가기 버튼을 BackButton.tsx로 분리
2. mypage, edit: 전체 아이템 감싸는 컨테이너 생성해 여백 gap으로 조절하도록 변경, 불필요한 div 제거
3. landing: 텍스트, 여백 등 일부 반응형 디자인 수정

[Refactor, Style] mypage, edit: 뒤로가기 버튼 분리, 여백 통일 / landing: 반응형 디자인 일부 수정

---

src/api/users.ts
src/components/card/ChangePassword.tsx
src/components/card/Profile.tsx
src/components/gnb/HeaderDashboard.tsx
src/components/table/invited/InvitedDashBoard.tsx
src/pages/dashboard/[dashboardId]/edit.tsx
src/pages/mypage.tsx
src/store/useUserStore.ts

1. useUserStore.ts에 닉네임과 프로필 업데이트 상태 관리 추가
2. Profile, mypage: useUserStore 연결해 프로필 변경 시 즉시 반영되도록 수정, 새로고침 제거
3. ChangePassword: 새로고침 제거

[Refactor, Style] Zustand 전역 상태 관리에 유저 정보 추가 / mypage: 프로필 변경 즉시 반영

---

src/pages/mypage.tsx

[Refactor] 불필요한 코드 제거

---

src/components/columnCard/CardList.tsx
src/components/columnCard/SortableCard.tsx

- 칼럼 카드 이동 기능을 추가하였습니다. 
- 아직 이동된 위치 저장은 안돼는 상태입니다.
- ![녹음 2025-04-09 215059](https://github.com/user-attachments/assets/889570ff-bb6a-4c40-8b82-31154c17c5dc)

[Feat] Column D&D 적용

---

src/components/columnCard/CardList.tsx
src/components/columnCard/Column.tsx
src/components/modalDashboard/CardDetail.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/modalInput/CardInput.tsx
src/components/modalInput/ToDoModal.tsx
src/components/table/member/MemberList.tsx
src/pages/dashboard/[dashboardId]/index.tsx

1. dashboard_index_Column, CardList: 칼럼 삭제, 카드 생성, 삭제, 수정 즉시 반영되도록 변경 & 새로고침 제거
2. Column_CardList: 마감일 빠른 순 정렬 기능 추가

[Refactor] Column, Card: 칼럼 삭제, 카드 생성, 삭제, 수정 즉시 반영 / 마감일 빠른 순 정렬

---

src/api/card.ts
src/components/card/ChangePassword.tsx
src/components/card/Profile.tsx
src/components/columnCard/CardList.tsx
src/components/columnCard/Column.tsx
src/components/modal/ChangeBebridge.tsx
src/components/modal/InviteDashboard.tsx
src/components/modalDashboard/CardDetail.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/modalInput/AssigneeSelect.tsx
src/components/modalInput/InputClassNames.ts
src/components/modalInput/ModalImage.tsx
src/components/modalInput/ModalInput.tsx
src/components/modalInput/ModalTextarea.tsx
src/components/modalInput/StatusSelect.tsx
src/components/modalInput/TaskModal.tsx
src/components/modalInput/ToDoModal.tsx
src/components/table/InviteRecords.tsx
src/components/table/member/MemberList.tsx

1. Card: 수정/생성 시 256자 이상 입력하면 에러 발생 -> maxLength 적용해 제한, 입력창 하단에 글자수 표시
2. Column: 카드 개수 아이콘에 10개까지만 카운트되던 것 size 10 -> 300 수정
3. Card: 제목 글자수 제한 추가(70자)
4. Card: 수정/생성 모달의 label, placeholder 등 text size 반응형 적용, 디자인 수정
5. toast: 띄어쓰기 수정

[Refactor, Fix] Card: 글자수 제한 에러 수정 & text size 반응형 적용

---

src/components/input/Input.tsx
src/components/sideMenu/SideMenu.tsx
src/pages/mydashboard.tsx
src/pages/signup.tsx

- 사이드 메뉴 선택시 대시보드 강조 CSS 수정
- 나의 대시보드 페이지에서 대시보드 생성 시 대시보드 카드 누락 해결
- 회원가입 페이지 - 닉네임 10자 제한 경고 추가

[Fix, Style, Refector] 사이드 메뉴 CSS 변경, MyDashboardPage에서 새로운 대시보드 생성 시 누락 해결

---

src/components/modalInput/CardInput.tsx

CardInput 반응형 리디자인 중 불필요해진 코드 삭제

[Chore] 불필요해진 코드 제거

---

src/api/card.ts
src/components/modalDashboard/CardDetail.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/modalInput/TaskModal.tsx

- 카드 수정 모달에서 담당자 선택 시, 선택된 담당자의 userId 기반으로 수정 API요청 전송
카드 수정 이후 cardData.assignee를 업데이트 하여 모달에서 즉시 반영되도록 개선

[Feat Fix Refector] 담당자 선택 갱신 수정

---

src/components/modalInput/ModalInput.tsx
src/styles/globals.css

- ![image](https://github.com/user-attachments/assets/8867fba3-8884-4bfb-b122-36a6a1fecc21)
- 모바일에서 datepicker 달력 팝업이 깨지는 오류를 수정하였습니다.

[Refector Style] 마감일 달력 팝업 CSS 커스텀

---

src/styles/globals.css

- 달력 Time 선택이 팝업 우측을 관통하는 문제를 해결하였습니다.

[Style] 달력 팝업 CSS 수정

---

src/api/card.ts
src/components/button/PaginationButton.tsx
src/components/columnCard/Card.tsx
src/components/columnCard/Column.tsx
src/components/modal/DeleteCheckModal.tsx
src/components/modal/DeleteModal.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/modalDashboard/Representative.tsx
src/components/modalDashboard/UpdateComment.tsx
src/components/modalInput/TaskModal.tsx
src/pages/dashboard/[dashboardId]/index.tsx
src/pages/mydashboard.tsx

1. TaskModal: 마감일 필수 설정 제거
(마감일 기재 없이 카드 생성/수정 가능, 마감일 없음으로 표시됨, 정렬 가장 뒤쪽으로 밀림)
2. TaskModal: 높이 윈도우 기준으로 변경
(기존 vw값으로 지정되어 모바일에서 주소창 on일 때 화면 높이를 넘어감)
3. Card: 카드/댓글 삭제 시 확인 모달 추가(공통 컴포넌트 DeleteModal.tsx 생성)
수정/삭제 시 toast 표시 추가
4. Card: 제목or내용 입력값이 공백 뿐일 때 등록되지 않도록 유효성 검사 옵션 추가
5. Column: 제목 길이 모바일 대응(break-words + max-w)

[Refactor, Style] TaskModal: 마감일 필수 설정 제거 / Card: 카드&댓글 삭제 확인 모달 추가, 제목&내용 공백 검사

---

src/components/modalInput/AssigneeSelect.tsx
src/components/modalInput/TaskModal.tsx

- ![image](https://github.com/user-attachments/assets/2e735f65-b0c8-4ccc-b09d-8dbff43bd6ba)
- 할일 생성/ 수정 모달의 담당자 사진이 없을시 랜덤 프로필이 뜨게 하였습니다.

[Fix] 담당자 랜덤 프로필 복구

---

src/components/modal/FormModal.tsx
src/components/modal/NewDashboard.tsx
src/components/modalInput/AssigneeSelect.tsx
src/components/modalInput/InputClassNames.ts
src/components/modalInput/ModalInput.tsx
src/components/modalInput/ModalTextarea.tsx
src/components/modalInput/StatusSelect.tsx
src/components/modalInput/TaskModal.tsx
src/pages/dashboard/[dashboardId]/index.tsx

1. FormModal, TaskModal: 모바일에서 인풋 창 클릭 시 zoon-in 기능 방지 목적으로 input text-16px 미만 수정
(모바일 브라우저 자체 기능이지만, zoom-in 후 다시 zoom-out 해야 해 불편을 초래한다고 판단해 방지하는 방향으로 수정함)

[Refactor] FormModal, TaskModal: 모바일 확대 방지 input text 최소 size 16px 변경

---

src/api/columns.ts
src/components/columnCard/Column.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/modalDashboard/UpdateComment.tsx
src/components/modalDashboard/formatDate.ts
src/components/modalInput/CardInput.tsx
src/components/modalInput/ModalImage.tsx
src/components/modalInput/ModalTextarea.tsx
src/components/modalInput/TaskModal.tsx
src/components/modalInput/TextButton.tsx
src/hooks/useCardDetailState.ts
src/hooks/useColumnStatus.ts
src/hooks/useTaskForm.ts
src/pages/dashboard/[dashboardId]/index.tsx

- 카드 생성/ 수정 모달의 카드 칼럼 상태 변경에 따른 이동 오류 해결
- ![image](https://github.com/user-attachments/assets/7c225470-7e6d-424e-91a6-ccde356c9416)

[Fix] 카드, 칼럼 상태 변경오류 해결

---

src/api/members.ts
src/components/button/GuestModeButton.tsx
src/components/columnCard/Card.tsx
src/components/landing/Section1.tsx
src/components/modalDashboard/CardDetailModal.tsx
src/components/modalInput/chips/TagColorChip.tsx

1. TaskModal: Type 연쇄 에러 발생해 훅 분리 전으로 롤백
2. Landing: 버튼 너비 반응형 적용으로 모바일 이하 대응
3. Card: 컨테이너 높이 반응형 적용, 프로필아이콘 정렬 수정
4. TagColorChip: Tag 색상 변경 용도 컬러칩 컴포넌트 생성, 기능 추후 구현 예정

[Fix, Style] TaskModal: 분리 전으로 롤백 / Landing: 버튼 너비 반응형 적용 / Card: 컨테이너 높이 반응형 적용

---

src/components/card/ChangePassword.tsx
src/components/landing/Section1.tsx

1. mypage: 비밀번호 경고 메시지 중복 표시 해결
2. Landing: 버튼 너비 조절

[Refactor] mypage: 비밀번호 경고 메시지 중복 표시 fix / Landing: 버튼 너비 조절

---

src/components/gnb/MemberListMenu.tsx
src/components/gnb/UserMenu.tsx
src/components/landing/Section1.tsx
src/components/modalInput/chips/SelectTagColorChip.tsx
src/components/table/invited/InvitedDashBoard.tsx
src/pages/signup.tsx

1. signup: 중복 이메일 가입 에러 toast 처리
-AxiosError로 response 409 조건문 처리
2. UserMenu, MemberListMenu: 드롭다운 메뉴 테두리 둥글기 추가(rounded-lg)
3. InvitedDashboard: 페이지 접근 시 깜빡임 fix
-초대 내역 데이터 fetching 중 초대 내역이 0일 때 출력되는 EmptyInvitations가 잠시 표시되는 현상이 발생해 수정

[Fix, Refactor] signup: 중복 이메일 가입 에러 토스트 처리 / InvitedDashboard: 컴포넌트 깜빡임 fix
